### ISSUE TITLE
Add deepin mirror to the server.

### ISSUE THREAD

**Issue by LoongWynn** [seuite/seuite-issues#2]
#### 项目名称与简介(Project Intro.)
Add deepin to this mirror service

#### 上游地址与镜像方法(How to Mirror)
[tuna mirror for deepin](https://mirrors.tuna.tsinghua.edu.cn/deepin/).
Download and sync
#### 其他信息(Other)
- 镜像大小(Mirror Size): 
not sure.

**Comment by c4yg70** [comment]
镜像大小 584.16G，
已计划于 2019/3/30 部署。
另：下次请用中文标题
